server:
  port: 8081
spring:
  boot:
    admin:
      client:
        url: http://localhost:8081/admin
      context-path: /admin



management:
  endpoints:
    web:
      exposure:
        include=health,info,metrics:
        include: "*"